version: '3.8'

services:
  xy-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xy-proxy
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
      - UUID=9afd1229-b893-40c1-84dd-51e7ce204913
      - CFIP=cdns.doon.eu.org
      - CFPORT=443
      - ARGO_PORT=8001
      - FILE_PATH=/app/tmp
      - PORT=3000
      - SUB_PATH=sub
      - UPLOAD_URL=
      - PROJECT_URL=
      - AUTO_ACCESS=false
      - NEZHA_SERVER=
      - NEZHA_PORT=
      - NEZHA_KEY=
      - ARGO_DOMAIN=
      - ARGO_AUTH=
      - NAME=
    volumes:
      - ./logs:/var/log/supervisor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s